services:
  webserver:
    build: .
    volumes:
      - ./evolutions:/app/evolutions
      - ./cat_evolution.json:/app/cat_evolution.json
      - ./layer_map.txt:/app/layer_map.txt
    ports:
      - "80:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 